-- 076_crop_varieties_batch2.sql
-- Сгенерировано scripts/gen-varieties-migration.js из docs/varieties/morkov.csv, docs/varieties/svekla.csv, docs/varieties/kapusta-belokochannaya.csv, docs/varieties/perec.csv, docs/varieties/luk-repchatyy.csv, docs/varieties/chesnok.csv, docs/varieties/redis.csv, docs/varieties/kabachok.csv, docs/varieties/baklazhan.csv, docs/varieties/tykva.csv.
-- Не редактировать руками — поправь исходный CSV и перегенерируй.

INSERT INTO crop_varieties (crop_id, name, ripening, harvest_days, harvest_doy_start, harvest_doy_end, is_hybrid, conditions, notes, source) VALUES
((SELECT id FROM crops WHERE name = 'Морковь'), 'Нантская 4', 'mid', 90, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (fermilon.ru, stroy-podskazka.ru, 7ogorod.ru), 2026-08-17: 78-108 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Морковь'), 'Шантенэ 2461', 'mid', 108, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (orton.ru, profermu.com, zelen.market), 2026-08-17: 100-115 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Морковь'), 'Тушон', 'early', 85, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (glav-dacha.ru, sortoved.ru, agronomu.com), 2026-08-17: 80-90 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Свёкла'), 'Бордо 237', 'mid', 90, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (stroy-podskazka.ru, orton.ru, sortoved.ru), 2026-08-17: 70-100 дней от всходов, среднеранний'),
((SELECT id FROM crops WHERE name = 'Свёкла'), 'Цилиндра', 'late', 115, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ferma.expert, fermilon.ru, 7ogorod.ru), 2026-08-17: 110-120 дней от всходов, среднепоздний'),
((SELECT id FROM crops WHERE name = 'Свёкла'), 'Египетская плоская', 'mid', 105, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (fermilon.ru, sortoved.ru, sad24.ru), 2026-08-17: 100-120 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Капуста белокочанная'), 'Слава 1305', 'mid', 110, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (klumba.guru, repka.online, rassadacvetov.com), 2026-08-17: 98-126 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Капуста белокочанная'), 'Июньская', 'early', 95, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (vniissok.com, tropic-garden.ru, antonovsad.ru), 2026-08-17: 90-105 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Капуста белокочанная'), 'Белорусская 455', 'late', 125, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (7ogorod.ru, agrognom.ru, dachnoedelo.ru), 2026-08-17: 120-130 дней от всходов, среднепоздний'),
((SELECT id FROM crops WHERE name = 'Перец'), 'Богатырь', 'mid', 128, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (antonovsad.ru, orchardo.ru, uogorod.ru), 2026-08-17: 115-145 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Перец'), 'Калифорнийское чудо', 'early', 115, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ferma.expert, antonovsad.ru, profermu.com), 2026-08-17: 100-129 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Перец'), 'Ласточка', 'mid', 122, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ferma.expert, antonovsad.ru, fermilon.ru), 2026-08-17: 116-130 дней от всходов, среднеранний'),
((SELECT id FROM crops WHERE name = 'Лук репчатый'), 'Штутгартер Ризен', 'early', 118, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (kp.ru, 7dach.ru, fermilon.ru), 2026-08-17: 115-120 дней от посева семенами до созревания репки'),
((SELECT id FROM crops WHERE name = 'Лук репчатый'), 'Центурион F1', 'early', 90, NULL, NULL, true, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ncsemena.ru, repka.online), 2026-08-17: 90 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Лук репчатый'), 'Стригуновский местный', 'early', 88, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (orton.ru, ogorodgid.ru, leplants.ru), 2026-08-17: 77-98 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Чеснок'), 'Любаша', 'autumn', NULL, NULL, NULL, false, 'any', 'Озимый; числовой срок из каталогов (88-98 дней) относится, вероятно, не к полному циклу посадка→уборка (у озимого чеснока это ~9-10 месяцев, см. crops.sowing_start_day=270), а к периоду от весеннего отрастания — риск неверной даты, поэтому harvest_days не заполнен, см. риски плана.', 'каталоги сортов, сверено 2+ источника (ferma.expert, sad24.ru, orton.ru), 2026-08-17: 88-98 дней — трактовка периода неоднозначна'),
((SELECT id FROM crops WHERE name = 'Редис'), '18 дней', 'early', 18, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (7dach.ru, sortoved.ru, rusfermer.net), 2026-08-17: 16-20 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Редис'), 'Сакса', 'mid', 23, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (stroy-podskazka.ru, dacha.expert, orton.ru), 2026-08-17: 20-25 дней от всходов, группа среднеспелых'),
((SELECT id FROM crops WHERE name = 'Редис'), 'Дуро', 'early', 25, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (agronom.expert, rosegardening.org, fermerok.info), 2026-08-17: 23-30 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Кабачок'), 'Грибовский 37', 'mid', 52, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (fermilon.ru, orton.ru, dachadecor.ru), 2026-08-17: 46-57 дней от всходов, среднеранний'),
((SELECT id FROM crops WHERE name = 'Кабачок'), 'Аэронавт', 'early', 46, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ferma.expert, stroy-podskazka.ru, dacha-dacha.ru), 2026-08-17: 46 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Кабачок'), 'Цукеша', 'early', 45, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ferma.expert, fermilon.ru, diz-cafe.com), 2026-08-17: 41-51 день от всходов'),
((SELECT id FROM crops WHERE name = 'Баклажан'), 'Алмаз', 'mid', 115, NULL, NULL, false, 'any', 'Разброс между источниками широкий (100-150 дней) — взято среднее по совпадающему диапазону 100-120.', 'каталоги сортов, сверено 2+ источника (ferma.expert, diz-cafe.com, bigsad.ru), 2026-08-17: 100-150 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Баклажан'), 'Чёрный красавец', 'mid', 118, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ferma.expert, stroy-podskazka.ru, tikvach.ru), 2026-08-17: 110-145 дней, чаще указывают 115-120'),
((SELECT id FROM crops WHERE name = 'Баклажан'), 'Робин Гуд', 'early', 95, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (fermilon.ru, stroy-podskazka.ru, repka.online), 2026-08-17: 90-100 дней от всходов, очень ранний'),
((SELECT id FROM crops WHERE name = 'Тыква'), 'Мускатная Прованская', 'late', 112, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ferma.expert, orton.ru, agromarket.ru), 2026-08-17: 110-115 дней от всходов'),
((SELECT id FROM crops WHERE name = 'Тыква'), 'Улыбка', 'early', 82, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ferma.expert, fermilon.ru, vhoz.ru), 2026-08-17: 80-85 дней от посадки'),
((SELECT id FROM crops WHERE name = 'Тыква'), 'Витаминная', 'late', 130, NULL, NULL, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ferma.expert, tikvach.ru), 2026-08-17: 130 дней от всходов')
ON CONFLICT (crop_id, name) DO NOTHING;
