-- 080_crop_varieties_batch4_perennials.sql
-- Сгенерировано scripts/gen-varieties-migration.js из docs/varieties/klubnika.csv, docs/varieties/malina.csv, docs/varieties/smorodina-chernaya.csv, docs/varieties/smorodina-krasnaya.csv, docs/varieties/smorodina-belaya.csv, docs/varieties/kryzhovnik.csv, docs/varieties/ezhevika.csv, docs/varieties/zhimolost-sedobnaya.csv, docs/varieties/yablonya.csv, docs/varieties/grusha.csv, docs/varieties/vishnya.csv, docs/varieties/chereshnya.csv, docs/varieties/sliva.csv.
-- Не редактировать руками — поправь исходный CSV и перегенерируй.

INSERT INTO crop_varieties (crop_id, name, ripening, harvest_days, harvest_doy_start, harvest_doy_end, is_hybrid, conditions, notes, source) VALUES
((SELECT id FROM crops WHERE name = 'Клубника'), 'Хоней', 'early', NULL, 140, 161, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (fermer.blog, orton.ru), 2026-08-17: конец мая — начало июня'),
((SELECT id FROM crops WHERE name = 'Клубника'), 'Зенга Зенгана', 'mid', NULL, 166, 181, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ferma.expert, ogorodum.ru), 2026-08-17: созревает в середине и на протяжении июня'),
((SELECT id FROM crops WHERE name = 'Клубника'), 'Альбион', 'mid', NULL, 145, 258, false, 'any', 'Ремонтантный сорт — плодоносит волнами весь сезон (конец мая — сентябрь), а не одно окно. Широкий диапазон отражает это, не погрешность измерения.', 'каталоги сортов, сверено 2+ источника (ferma.expert, biosad.ua), 2026-08-17: последняя декада мая — сентябрь'),
((SELECT id FROM crops WHERE name = 'Малина'), 'Новость Кузьмина', 'early', NULL, 166, 196, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (stroy-podskazka.ru, fermilon.ru), 2026-08-17: ранний сорт, середина июня — середина июля'),
((SELECT id FROM crops WHERE name = 'Малина'), 'Геракл', 'late', NULL, 182, 273, false, 'any', 'Ремонтантный, 2 волны плодоношения (начало июля и с августа до заморозков) — окно широкое намеренно.', 'каталоги сортов, сверено 2+ источника (stroy-podskazka.ru, orton.ru), 2026-08-17: начало июля, затем август — заморозки'),
((SELECT id FROM crops WHERE name = 'Малина'), 'Бабье лето', 'late', NULL, 182, 273, false, 'any', 'Ремонтантный сорт, точных дат в источниках нет — окно по общему признаку ремонтантности (июль — заморозки).', 'каталоги сортов (stroy-podskazka.ru), 2026-08-17: ремонтантный, без точных дат'),
((SELECT id FROM crops WHERE name = 'Смородина чёрная'), 'Селеченская', 'early', NULL, 182, 196, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (vniispk.ru, agropedia.ru), 2026-08-17: первая половина июля'),
((SELECT id FROM crops WHERE name = 'Смородина чёрная'), 'Пигмей', 'mid', NULL, 176, 191, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (xn--80akvccf.xn--p1ai, vniispk.ru), 2026-08-17: конец июня — начало июля'),
((SELECT id FROM crops WHERE name = 'Смородина чёрная'), 'Валовая', 'mid', NULL, NULL, NULL, false, 'any', 'Числовых сроков созревания в источниках не нашлось — только название сорта в списке. harvest_doy не заполнен.', 'каталоги сортов, 2026-08-17: без данных о сроке'),
((SELECT id FROM crops WHERE name = 'Смородина красная'), 'Йонкер ван Тетс', 'mid', NULL, 196, 213, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (vniispk.ru, nikogarden.ru), 2026-08-17: середина июля — начало августа'),
((SELECT id FROM crops WHERE name = 'Смородина красная'), 'Ненаглядная', 'mid', NULL, 176, 196, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ferma.expert, smorodina1.ru), 2026-08-17: конец июня — начало июля'),
((SELECT id FROM crops WHERE name = 'Смородина белая'), 'Смольяниновская', 'mid', NULL, 176, 206, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (poferme.com, remontanta.ru), 2026-08-17: конец июня — июль'),
((SELECT id FROM crops WHERE name = 'Смородина белая'), 'Уральская белая', 'early', NULL, 176, 206, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (vniispk.ru, rastisad.ru), 2026-08-17: конец июня — июль'),
((SELECT id FROM crops WHERE name = 'Крыжовник'), 'Малахит', 'mid', NULL, 206, 227, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (fermilon.ru, profermu.com), 2026-08-17: конец июля — середина августа'),
((SELECT id FROM crops WHERE name = 'Крыжовник'), 'Финик', 'late', NULL, 206, 232, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (fermilon.ru, kryzhovnik.info), 2026-08-17: техническая спелость конец июля, полная — середина августа'),
((SELECT id FROM crops WHERE name = 'Ежевика'), 'Агавам', 'mid', NULL, 220, 232, false, 'any', NULL, 'каталоги сортов (fermilon.ru), 2026-08-17: середина августа'),
((SELECT id FROM crops WHERE name = 'Ежевика'), 'Торнфри', 'late', NULL, 213, 258, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (stroy-podskazka.ru, sazhaemvsadu.ru), 2026-08-17: август — середина сентября'),
((SELECT id FROM crops WHERE name = 'Жимолость съедобная'), 'Голубое веретено', 'early', NULL, 152, 166, false, 'any', NULL, 'каталоги сортов (fermilon.ru), 2026-08-17: первая половина июня'),
((SELECT id FROM crops WHERE name = 'Жимолость съедобная'), 'Бакчарский великан', 'mid', NULL, 161, 171, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (7dach.ru, bigsad.ru), 2026-08-17: середина июня'),
((SELECT id FROM crops WHERE name = 'Яблоня'), 'Белый налив', 'summer', NULL, 206, 220, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ferma.expert, kp.ru), 2026-08-17: конец июля — первая декада августа'),
((SELECT id FROM crops WHERE name = 'Яблоня'), 'Мельба', 'autumn', NULL, 227, 258, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ferma.expert, antonovsad.ru), 2026-08-17: середина августа — середина сентября'),
((SELECT id FROM crops WHERE name = 'Яблоня'), 'Антоновка', 'autumn', NULL, 250, 265, false, 'any', NULL, 'каталоги сортов (lenta.ru и др.), 2026-08-17: к середине сентября'),
((SELECT id FROM crops WHERE name = 'Груша'), 'Лада', 'summer', NULL, 206, 227, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (kp.ru, dachamechty.ru), 2026-08-17: конец июля — середина августа'),
((SELECT id FROM crops WHERE name = 'Груша'), 'Чижовская', 'summer', NULL, 206, 227, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (kp.ru, profermu.com), 2026-08-17: конец июля — август'),
((SELECT id FROM crops WHERE name = 'Груша'), 'Конференция', 'autumn', NULL, 263, 284, false, 'any', NULL, 'каталоги сортов (ferma.expert), 2026-08-17: конец сентября — октябрь'),
((SELECT id FROM crops WHERE name = 'Вишня'), 'Владимирская', 'mid', NULL, 191, 201, false, 'any', NULL, 'каталоги сортов (kp.ru), 2026-08-17: середина июля'),
((SELECT id FROM crops WHERE name = 'Вишня'), 'Шоколадница', 'mid', NULL, 191, 201, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (stroy-podskazka.ru, vsadu.ru), 2026-08-17: вторая декада июля'),
((SELECT id FROM crops WHERE name = 'Вишня'), 'Любская', 'mid', NULL, NULL, NULL, false, 'any', 'Числовых сроков не нашлось — источники упоминают её только как опылитель для Владимирской. harvest_doy не заполнен.', 'каталоги сортов, 2026-08-17: без данных о сроке'),
((SELECT id FROM crops WHERE name = 'Черешня'), 'Валерий Чкалов', 'early', NULL, 152, 166, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (vniispk.ru, fermilon.ru), 2026-08-17: 1 декада июня, в Подмосковье — до середины июля'),
((SELECT id FROM crops WHERE name = 'Черешня'), 'Ипуть', 'early', NULL, 166, 186, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (xn--80akvccf.xn--p1ai, antonovsad.ru), 2026-08-17: середина июня — начало июля'),
((SELECT id FROM crops WHERE name = 'Слива'), 'Венгерка московская', 'late', NULL, 258, 273, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (ferma.expert, sortoved.ru), 2026-08-17: вторая половина сентября'),
((SELECT id FROM crops WHERE name = 'Слива'), 'Ренклод колхозный', 'mid', NULL, 227, 237, false, 'any', NULL, 'каталоги сортов, сверено 2+ источника (xn--80akvccf.xn--p1ai, stroy-podskazka.ru), 2026-08-17: 2 декада августа, 15-25 августа'),
((SELECT id FROM crops WHERE name = 'Слива'), 'Стенли', 'late', NULL, NULL, NULL, false, 'any', 'Только качественное описание («позднеспелый»), числового окна не найдено.', 'каталоги сортов (glav-dacha.ru), 2026-08-17: без числового срока')
ON CONFLICT (crop_id, name) DO NOTHING;
