package ru.dachakalend.app.ui.plantings

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Info
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.style.TextDecoration
import ru.dachakalend.app.data.model.ActionLog
import ru.dachakalend.app.data.model.CareTask
import ru.dachakalend.app.data.model.Planting
import ru.dachakalend.app.ui.actions.careTaskActionType
import java.time.LocalDate
import java.time.format.DateTimeFormatter

private val ACTION_LABELS = mapOf(
    "watering"      to "💧 Полив",
    "fertilizing"   to "🌿 Подкормка",
    "treatment"     to "🛡️ Обработка",
    "pricking_out"  to "🪴 Пикировка",
    "transplanting" to "🌱 Высадка",
    "tying"         to "🪢 Подвязка",
    "pinching"      to "✂️ Пасынкование",
    "hilling"       to "⛏️ Окучивание",
    "pruning"       to "🌿 Обрезка",
    "weeding"       to "🌾 Прополка",
    "loosening"     to "🔨 Рыхление",
    "thinning"      to "✂️ Прореживание",
    "runner_removal" to "🌿 Удаление усов",
    "bolt_removal"  to "🧄 Удаление стрелок",
    "deflowering"   to "🌸 Удаление цветков",
    "staking"       to "🪵 Установка опоры",
    "other"         to "📋 Другое"
)

private fun isAutoGeneratedNote(note: String, type: String, cropName: String?): Boolean {
    val label = ACTION_LABELS[type]?.replace(Regex("^\\S+\\s"), "") ?: return false
    val crop  = cropName ?: return false
    return note == "$label: $crop" || note == "$label — $crop" || note == "$label - $crop"
}

private fun formatShort(iso: String): String = try {
    val date = java.time.OffsetDateTime.parse(iso)
    "%02d.%02d.%02d".format(date.dayOfMonth, date.monthValue, date.year % 100)
} catch (_: Exception) {
    try {
        val d = LocalDate.parse(iso.take(10))
        "%02d.%02d.%02d".format(d.dayOfMonth, d.monthValue, d.year % 100)
    } catch (_: Exception) { iso }
}

private fun plantedDate(sownAt: String?): LocalDate? = sownAt?.let {
    runCatching { LocalDate.parse(it.take(10)) }.getOrNull()
}

private fun fmtDate(d: LocalDate): String =
    "%02d.%02d.%02d".format(d.dayOfMonth, d.monthValue, d.year % 100)

// ── Статус работы в расписании ───────────────────────────────────────────────
private enum class SchedStatus { DONE, MISSED, UPCOMING, NEUTRAL }
private data class SchedRow(val name: String, val dateStr: String, val date: LocalDate, val status: SchedStatus)

private fun actionLocalDate(iso: String): LocalDate? =
    runCatching { java.time.OffsetDateTime.parse(iso).toLocalDate() }.getOrNull()
        ?: runCatching { LocalDate.parse(iso.take(10)) }.getOrNull()

// Какие action_type закрывают строку расписания. null → статус не вычисляем (нейтрально).
private fun rowActionTypes(name: String): Set<String>? = when {
    name.contains("Пересадка", true) || name.contains("пикировк", true) -> setOf("transplanting", "pricking_out")
    name.contains("урожай", true) -> null  // урожай логируется отдельно (не через действия)
    else -> careTaskActionType(name).let { if (it == "other") null else setOf(it) }
}

/**
 * Строит расписание работ со статусом: DONE (выполнено), MISSED (просрочено),
 * UPCOMING (предстоит), NEUTRAL (статус не определяем — урожай).
 * «Выполнено» = есть действие нужного типа в окне [дата_работы, дата_след_повтора).
 */
private fun buildSchedule(
    transplantDays: Int?,
    careTasks: List<CareTask>?,
    harvestDays: Int?,
    wateringFreqDays: Int?,
    conditions: String?,
    sowingMethod: String?,
    planted: LocalDate,
    actions: List<ActionLog>,
    today: LocalDate
): List<SchedRow> {
    val rows = mutableListOf<SchedRow>()
    fun statusOf(name: String, date: LocalDate, next: LocalDate?): SchedStatus {
        val types = rowActionTypes(name) ?: return SchedStatus.NEUTRAL
        val done = actions.any { a ->
            a.type in types && actionLocalDate(a.loggedAt)?.let { d ->
                !d.isBefore(date) && (next == null || d.isBefore(next))
            } == true
        }
        return when {
            done                 -> SchedStatus.DONE
            date.isBefore(today) -> SchedStatus.MISSED
            else                 -> SchedStatus.UPCOMING
        }
    }
    // Высадка в грунт — только для рассадного способа; прямой посев не пересаживают.
    if (sowingMethod != "direct") transplantDays?.let {
        val d = planted.plusDays(it.toLong())
        rows += SchedRow("🌿 Пересадка/пикировка", fmtDate(d), d, statusOf("Пересадка", d, null))
    }
    val limit = harvestDays ?: 120
    careTasks?.forEach { task ->
        val occ = mutableListOf<LocalDate>()
        var offset = task.dayOffset
        while (offset <= limit) {
            occ += planted.plusDays(offset.toLong())
            if (task.repeatDays == null) break
            offset += task.repeatDays
        }
        occ.forEachIndexed { i, d ->
            rows += SchedRow(task.name, fmtDate(d), d, statusOf(task.name, d, occ.getOrNull(i + 1)))
        }
    }
    // 💧 Полив — предстоящие отметки каждые interval дней (теплица ×0.8, как на бэке).
    // Показываем только будущие: прошлые фактические поливы видны в «Истории действий»,
    // а ряд «просрочено» для частого полива был бы визуальным шумом.
    wateringFreqDays?.let { freq ->
        val interval = if (conditions == "greenhouse") maxOf(1, Math.round(freq * 0.8).toInt()) else freq
        if (interval >= 1) {
            val wLimit = minOf(harvestDays ?: 120, 120)
            var offset = interval
            var shown = 0
            while (offset <= wLimit && shown < 40) {
                val d = planted.plusDays(offset.toLong())
                if (!d.isBefore(today)) {
                    rows += SchedRow("💧 Полив", fmtDate(d), d, SchedStatus.UPCOMING)
                    shown++
                }
                offset += interval
            }
        }
    }
    harvestDays?.let {
        val d = planted.plusDays(it.toLong())
        rows += SchedRow("🌾 Сбор урожая", fmtDate(d), d, SchedStatus.NEUTRAL)
    }
    return rows.sortedBy { it.date }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PlantingInfoBottomSheet(
    planting: Planting,
    onDismiss: () -> Unit,
    onCropDetail: (Int) -> Unit,
    viewModel: PlantingInfoViewModel = hiltViewModel()
) {
    val state by viewModel.uiState.collectAsState()

    LaunchedEffect(planting.id) {
        viewModel.reset()
        viewModel.load(planting.id, planting.cropId)
    }

    val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)

    ModalBottomSheet(
        onDismissRequest = onDismiss,
        sheetState = sheetState,
        windowInsets = WindowInsets(0)
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 16.dp)
                .padding(bottom = 32.dp)
                .navigationBarsPadding(),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Заголовок
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    planting.cropName ?: "Посадка",
                    style = MaterialTheme.typography.titleLarge,
                    fontWeight = FontWeight.Bold
                )
                TextButton(onClick = { onCropDetail(planting.cropId) }) {
                    Icon(Icons.Default.Info, contentDescription = null, modifier = Modifier.size(16.dp))
                    Spacer(Modifier.width(4.dp))
                    Text("О культуре")
                }
            }

            if (state.isLoading) {
                Box(Modifier.fillMaxWidth().height(100.dp), contentAlignment = Alignment.Center) {
                    CircularProgressIndicator()
                }
            } else {
                val planted = plantedDate(planting.sownAt)

                // ── 1. Основная информация ────────────────────────────────
                InfoSection(title = "Посадка") {
                    InfoRow2("Дата посадки", planting.sownAt?.let { formatShort(it) } ?: "—")
                    InfoRow2("Условия", if (planting.conditions == "greenhouse") "🏠 Теплица" else "🌱 Грунт")
                    InfoRow2("Количество растений", "${planting.quantity ?: 1} шт.")
                    // Ожидаемый урожай = количество × урожайность с куста (если известна для культуры)
                    planting.yieldPerPlantKg?.let { perPlant ->
                        val expected = perPlant * (planting.quantity ?: 1)
                        val s = "%.1f".format(expected).removeSuffix(",0").removeSuffix(".0")
                        InfoRow2("Ожидаемый урожай", "~$s кг")
                    }
                }

                // ── 2. Расчётные даты процессов ───────────────────────────
                val crop = state.crop
                if (planted != null && crop != null) {
                    val schedule = buildSchedule(
                        transplantDays   = crop.transplantDays,
                        careTasks        = crop.careTasks,
                        harvestDays      = crop.harvestDays,
                        wateringFreqDays = crop.wateringFreqDays,
                        conditions       = planting.conditions,
                        sowingMethod     = planting.sowingMethod,
                        planted          = planted,
                        actions          = state.recentActions,
                        today            = LocalDate.now()
                    )
                    if (schedule.isNotEmpty()) {
                        InfoSection(title = "Расписание работ") {
                            Text(
                                "🟢 выполнено · 🔴 просрочено · ⚪ предстоит",
                                style = MaterialTheme.typography.labelSmall,
                                color = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                            schedule.forEach { row -> SchedRowView(row) }
                        }
                    }
                }

                // ── 3. История действий ───────────────────────────────────
                InfoSection(title = "История действий") {
                    if (state.recentActions.isEmpty()) {
                        Text(
                            "Действий пока не записано",
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    } else {
                        state.recentActions.forEach { action ->
                            val userNote = action.notes?.takeIf { note ->
                                note.isNotBlank() && !isAutoGeneratedNote(note, action.type, action.cropName)
                            }
                            val typeLabel = buildString {
                                append(ACTION_LABELS[action.type] ?: action.type)
                                if (userNote != null) append(": $userNote")
                            }
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceBetween
                            ) {
                                Text(
                                    typeLabel,
                                    style = MaterialTheme.typography.bodyMedium,
                                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                                    modifier = Modifier.weight(1f)
                                )
                                Text(formatShort(action.loggedAt), style = MaterialTheme.typography.bodyMedium)
                            }
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun InfoSection(title: String, content: @Composable ColumnScope.() -> Unit) {
    Card(modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
            Text(title, style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold)
            HorizontalDivider(modifier = Modifier.padding(vertical = 4.dp))
            content()
        }
    }
}

@Composable
private fun SchedRowView(row: SchedRow) {
    val muted = MaterialTheme.colorScheme.onSurfaceVariant
    val (color, marker, strike) = when (row.status) {
        SchedStatus.DONE     -> Triple(muted, "🟢 ", true)
        SchedStatus.MISSED   -> Triple(MaterialTheme.colorScheme.error, "🔴 ", false)
        SchedStatus.UPCOMING -> Triple(MaterialTheme.colorScheme.onSurface, "⚪ ", false)
        SchedStatus.NEUTRAL  -> Triple(muted, "", false)
    }
    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
        Text(
            "$marker${row.name}",
            style = MaterialTheme.typography.bodyMedium,
            color = color,
            textDecoration = if (strike) TextDecoration.LineThrough else null,
            modifier = Modifier.weight(1f)
        )
        Text(
            row.dateStr,
            style = MaterialTheme.typography.bodyMedium,
            color = color,
            fontWeight = if (row.status == SchedStatus.MISSED) FontWeight.Bold else FontWeight.Normal
        )
    }
}

@Composable
private fun InfoRow2(label: String, value: String) {
    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
        Text(
            label,
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            modifier = Modifier.weight(1f)
        )
        Text(value, style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.Bold)
    }
}
