package ru.dachakalend.app.ui.journal

import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.background
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.hilt.navigation.compose.hiltViewModel
import ru.dachakalend.app.data.model.ActionLog
import ru.dachakalend.app.ui.theme.NunitoFamily

private val ACTION_LABELS_PLAIN = mapOf(
    "watering"      to "Полить",
    "fertilizing"   to "Подкормка",
    "treatment"     to "Обработка",
    "pricking_out"  to "Пикировка",
    "transplanting" to "Высадить в грунт",
    "tying"         to "Подвязка",
    "pinching"      to "Пасынкование",
    "hilling"       to "Окучивание",
    "pruning"       to "Обрезка",
    "weeding"       to "Прополка",
    "loosening"     to "Рыхление",
    "other"         to "Другое"
)

private fun isAutoGeneratedNote(note: String, type: String, cropName: String?): Boolean {
    val crop = cropName ?: return false
    val candidates = listOfNotNull(ACTION_LABELS[type], ACTION_LABELS_PLAIN[type])
    return candidates.any { label ->
        note == "$label: $crop" || note == "$label — $crop" || note == "$label - $crop"
    }
}

private val ACTION_LABELS = mapOf(
    "watering"      to "💧 Полив",
    "fertilizing"   to "🌿 Подкормка",
    "treatment"     to "🛡️ Обработка",
    "pricking_out"  to "🪴 Пикировка",
    "transplanting" to "🌱 Высадка",
    "tying"         to "🪢 Подвязка",
    "pinching"      to "✂️ Пасынкование",
    "hilling"       to "⛏️ Окучивание",
    "pruning"       to "🌿 Обрезка",
    "weeding"       to "🌾 Прополка",
    "loosening"     to "🔨 Рыхление",
    "other"         to "📋 Другое"
)

private fun formatDate(iso: String): String = try {
    val d = java.time.LocalDate.parse(iso)
    "%02d.%02d.%d".format(d.dayOfMonth, d.monthValue, d.year)
} catch (_: Exception) { iso }

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun JournalScreen(
    onBack: () -> Unit,
    viewModel: JournalViewModel = hiltViewModel()
) {
    val state by viewModel.uiState.collectAsState()
    var filterExpanded by remember { mutableStateOf(false) }

    Scaffold(
        containerColor = MaterialTheme.colorScheme.background,
        topBar = {
            TopAppBar(
                title = {
                    Text(
                        "Журнал действий",
                        fontFamily = NunitoFamily,
                        fontWeight = FontWeight.Black,
                        color = MaterialTheme.colorScheme.onBackground
                    )
                },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Назад")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.background
                ),
                actions = {
                    if (state.allCrops.isNotEmpty()) {
                        Box {
                            TextButton(onClick = { filterExpanded = true }) {
                                Text(
                                    text = state.cropFilter ?: "Все культуры",
                                    fontFamily = NunitoFamily,
                                    fontWeight = FontWeight.Bold
                                )
                            }
                            DropdownMenu(
                                expanded = filterExpanded,
                                onDismissRequest = { filterExpanded = false }
                            ) {
                                DropdownMenuItem(
                                    text = { Text("Все культуры", fontFamily = NunitoFamily) },
                                    onClick = { viewModel.setCropFilter(null); filterExpanded = false }
                                )
                                state.allCrops.forEach { crop ->
                                    DropdownMenuItem(
                                        text = { Text(crop, fontFamily = NunitoFamily) },
                                        onClick = { viewModel.setCropFilter(crop); filterExpanded = false }
                                    )
                                }
                            }
                        }
                    }
                }
            )
        }
    ) { padding ->
        when {
            state.isLoading -> Box(
                Modifier.fillMaxSize().padding(padding),
                contentAlignment = Alignment.Center
            ) { CircularProgressIndicator(color = MaterialTheme.colorScheme.primary) }

            state.filteredActions.isEmpty() -> Box(
                Modifier
                    .fillMaxSize()
                    .background(MaterialTheme.colorScheme.background)
                    .padding(padding),
                contentAlignment = Alignment.Center
            ) {
                Text(
                    if (state.cropFilter != null) "Нет действий для выбранной культуры"
                    else "Действий пока нет",
                    fontFamily = NunitoFamily,
                    fontWeight = FontWeight.SemiBold,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }

            else -> LazyColumn(
                modifier = Modifier
                    .background(MaterialTheme.colorScheme.background)
                    .padding(padding),
                contentPadding = PaddingValues(16.dp),
                verticalArrangement = Arrangement.spacedBy(4.dp)
            ) {
                state.groupedByDate.entries.sortedByDescending { it.key }.forEach { (date, logs) ->
                    item {
                        Text(
                            text = formatDate(date),
                            fontFamily = NunitoFamily,
                            fontWeight = FontWeight.Black,
                            fontSize = 13.sp,
                            color = MaterialTheme.colorScheme.primary,
                            modifier = Modifier.padding(top = 12.dp, bottom = 4.dp)
                        )
                    }
                    items(logs) { log ->
                        JournalEntry(
                            log = log,
                            onDelete = { viewModel.deleteAction(log.id) }
                        )
                    }
                }
            }
        }
    }
}

@OptIn(ExperimentalFoundationApi::class)
@Composable
private fun JournalEntry(log: ActionLog, onDelete: () -> Unit) {
    var showConfirm by remember { mutableStateOf(false) }

    if (showConfirm) {
        AlertDialog(
            onDismissRequest = { showConfirm = false },
            title = {
                Text("Удалить запись?", fontFamily = NunitoFamily, fontWeight = FontWeight.Black)
            },
            text = {
                val label = ACTION_LABELS[log.type] ?: log.type
                val crop  = log.cropName?.let { " — $it" } ?: ""
                Text(
                    "«$label$crop» будет удалено без возможности восстановления.",
                    fontFamily = NunitoFamily,
                    fontWeight = FontWeight.SemiBold
                )
            },
            confirmButton = {
                TextButton(onClick = { showConfirm = false; onDelete() }) {
                    Text("Удалить", color = MaterialTheme.colorScheme.error,
                        fontFamily = NunitoFamily, fontWeight = FontWeight.Black)
                }
            },
            dismissButton = {
                TextButton(onClick = { showConfirm = false }) {
                    Text("Отмена", fontFamily = NunitoFamily, fontWeight = FontWeight.Bold)
                }
            }
        )
    }

    Card(
        modifier = Modifier
            .fillMaxWidth()
            .combinedClickable(
                onClick = {},
                onLongClick = { showConfirm = true }
            ),
        shape = RoundedCornerShape(22.dp),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
        elevation = CardDefaults.cardElevation(defaultElevation = 3.dp)
    ) {
        Row(
            modifier = Modifier.padding(horizontal = 12.dp, vertical = 10.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            Text(
                text = ACTION_LABELS[log.type] ?: log.type,
                fontFamily = NunitoFamily,
                fontWeight = FontWeight.SemiBold,
                fontSize = 14.sp,
                color = MaterialTheme.colorScheme.onBackground,
                modifier = Modifier.weight(1f)
            )
            Column(horizontalAlignment = Alignment.End) {
                Text(
                    text = log.cropName ?: "",
                    fontFamily = NunitoFamily,
                    fontSize = 12.sp,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
                val userNote = log.notes?.takeIf { note ->
                    note.isNotBlank() && !isAutoGeneratedNote(note, log.type, log.cropName)
                }
                if (userNote != null) {
                    Text(
                        text = userNote,
                        fontFamily = NunitoFamily,
                        fontSize = 12.sp,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }
        }
    }
}


